### PR TITLE
Added option for an SSL certificate chain to lumberjack server

### PR DESCRIPTION
**Pull request by thefinn93**
I tested it with logstash-forwarder and it worked well. I've submitted a pull request at https://github.com/logstash-plugins/logstash-input-lumberjack/pull/30 to make use of these changes

### CODE REVIEW

**Comment by suyograo** [comment]
@thefinn93 can you please sign the CLA? https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

**Comment by thefinn93** [comment]
Done

**Comment by suyograo** [comment]
@thefinn93 thanks, this patch has been submitted with `@finn.io` email address. Can you please sign the CLA with this address? Also can you rebase?

**Comment by thefinn93** [comment]
There we go, should all be good.

**Comment by cspenceiv** [comment]
As I was preparing to send my pull request for the same issue, I decided to still submit my request as an alternative solution.

Note that my solution does not require changes to any other code using the Server Class.

**Comment by thefinn93** [comment]
Ah nice, much cleaner than mine. +1 for #20

**Comment by cspenceiv** [comment]
Thank you!

**Comment by suyograo** [comment]
Closing this in favor of #20

**Pull request closed without merging**
